name: trigger by parameter
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'source branch'
      destination_branch:
        description: 'destination branch'

jobs:
  check-parameter:
    runs-on: ubuntu-latest
    steps:
       - name: echo parameter
         run: echo "${{ github.event.inputs.source_branch }} , ${{ github.event.inputs.destination_branch }}"
       - name: create pull request with parameters
         run: |
              curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ github.repository }}/pulls \
                  -d '{"title":"change pull request","body":"Please pull these awesome changes in!","head":"${{ github.event.inputs.destination_branch }}","base":"${{ github.event.inputs.source_branch }}"}'
