name: trigger by parameter
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'source branch'
      destination_branch:
        description: 'destination branch'

jobs:
  check-parameter:
    runs-on: ubuntu-latest
    steps:
       - name: echo parameter
         run: echo "${{ github.event.inputs.source_branch }} , ${{ github.event.inputs.destination_branch }}"
    
      
