name: trigger by parameter
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'source branch'
        required: false
        default: 'main'
      destination_branch:
        description: 'destination branch'
        required: true
        
   
      
